name: Publish and Release

on:
  push:
    tags: ["v*"]  # Publish on tags matching "v*", eg. "v1.0.0"
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    uses: glenn20/python-ci/.github/workflows/test.yaml@main
    with:
      os: '["ubuntu-latest", "windows-latest", "macos-latest"]'
      python-version: '["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]'

  build:
    name: Build
    needs: tests
    uses: glenn20/python-ci/.github/workflows/build.yaml@main

  publish-test:
    name: Publish to test.pypi
    needs: build
    uses: ./.github/workflows/publish.yaml
    with:
      pypi: test.pypi
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing!

  publish-pypi:
    name: Publish to pypi
    needs: publish-test
    uses: ./.github/workflows/publish.yaml
    with:
      pypi: pypi
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing!

  github-release:
    name: Create GitHub release
    uses: glenn20/python-ci/.github/workflows/release.yaml@main
    needs: publish-pypi
    permissions:
      contents: write  # IMPORTANT: mandatory for github release
      id-token: write  # IMPORTANT: mandatory for github release
